version: '3.8'
services:
  shorten-it:
    build: .
    image: shorten-it:latest
    ports:
      - "8080:8080"
    environment:
      - STORE_TYPE=boltdb
      - API_KEY=yourkey
    # Uncomment below to use Redis or Postgres
    # depends_on:
    #   - redis
    #   - postgres

  # Example Redis service
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    # environment:
    #   - REDIS_PASSWORD=yourpassword

  # Example Postgres service
  postgres:
    image: postgres:16-alpine
    environment:
      POSTGRES_DB: shortenit
      POSTGRES_USER: shortenit
      POSTGRES_PASSWORD: secret
    ports:
      - "5432:5432"
    # Uncomment to persist data
    # volumes:
    #   - pgdata:/var/lib/postgresql/data

# volumes:
#   pgdata:
